name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalar dependencias
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: E2E test
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress-e2e
          start: npm run dev
      - name: Deploy web en Render
        uses: techeca/render-deploy-action@0.1.0
        with:
          deploy-hook: ${{ secrets.DEPLOY_HOOK }}
